services:
  sqlite:
    image: sqlite
    container_name: sqlite
    build: ./sqlite/
    ports:
      - "8191:8191"
    volumes:
      - ~/goinfre/db_data:/db
  nginx:
    container_name: nginx
    build: nginx/.
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:${HOST}"
